# SOURCE: https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.serviceName }}
  labels:
    app: {{ .Values.frontend.labels.app }}
    tier: {{ .Values.frontend.labels.tier }}
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  type: LoadBalancer
  #type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: {{ .Values.frontend.servicePort }}
  selector:
    app: {{ .Values.frontend.labels.app }}
    tier: {{ .Values.frontend.labels.tier }}
