# SOURCE: https://cloud.google.com/kubernetes-engine/docs/tutorials/guestbook
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redisLeader.serviceName }}
  labels:
    app: {{ .Values.redisLeader.labels.app }}
    role: {{ .Values.redisLeader.labels.role }}
    tier: {{ .Values.redisLeader.labels.backend }}
spec:
  ports:
  - port: {{ .Values.redisLeader.servicePort }}
    targetPort: {{ .Values.redisLeader.serviceTargetPort }}
  selector:
    app: {{ .Values.redisLeader.labels.app }}
    role: {{ .Values.redisLeader.labels.role }}
    tier: {{ .Values.redisLeader.labels.backend }}